CREATE SCHEMA public;

CREATE TABLE public.version (
	id SERIAL NOT NULL, 
	layer_id VARCHAR NOT NULL, 
	version VARCHAR NOT NULL, 
	epoch TIMESTAMP WITHOUT TIME ZONE, 
	date_added TIMESTAMP WITHOUT TIME ZONE, 
	default_version BOOLEAN NOT NULL, 
	catalogue_metadata JSONB, 
	PRIMARY KEY (id), 
	CONSTRAINT _layer_id_version_uc UNIQUE (layer_id, version)
)

;

CREATE TABLE public.source (
	id SERIAL NOT NULL, 
	name VARCHAR NOT NULL, 
	"RAJ2000" FLOAT NOT NULL, 
	"DECJ2000" FLOAT NOT NULL, 
	"Heal_Pix_Position" BIGINT NOT NULL, 
	version INTEGER NOT NULL, 
	"I_76" FLOAT, 
	"MajorAxis_76" FLOAT, 
	"MinorAxis_76" FLOAT, 
	"Orientation_76" FLOAT, 
	"I_84" FLOAT, 
	"MajorAxis_84" FLOAT, 
	"MinorAxis_84" FLOAT, 
	"Orientation_84" FLOAT, 
	"I_92" FLOAT, 
	"MajorAxis_92" FLOAT, 
	"MinorAxis_92" FLOAT, 
	"Orientation_92" FLOAT, 
	"I_99" FLOAT, 
	"MajorAxis_99" FLOAT, 
	"MinorAxis_99" FLOAT, 
	"Orientation_99" FLOAT, 
	"I_107" FLOAT, 
	"MajorAxis_107" FLOAT, 
	"MinorAxis_107" FLOAT, 
	"Orientation_107" FLOAT, 
	"I_115" FLOAT, 
	"MajorAxis_115" FLOAT, 
	"MinorAxis_115" FLOAT, 
	"Orientation_115" FLOAT, 
	"I_122" FLOAT, 
	"MajorAxis_122" FLOAT, 
	"MinorAxis_122" FLOAT, 
	"Orientation_122" FLOAT, 
	"I_130" FLOAT, 
	"MajorAxis_130" FLOAT, 
	"MinorAxis_130" FLOAT, 
	"Orientation_130" FLOAT, 
	"I_143" FLOAT, 
	"MajorAxis_143" FLOAT, 
	"MinorAxis_143" FLOAT, 
	"Orientation_143" FLOAT, 
	"I_151" FLOAT, 
	"MajorAxis_151" FLOAT, 
	"MinorAxis_151" FLOAT, 
	"Orientation_151" FLOAT, 
	"I_158" FLOAT, 
	"MajorAxis_158" FLOAT, 
	"MinorAxis_158" FLOAT, 
	"Orientation_158" FLOAT, 
	"I_166" FLOAT, 
	"MajorAxis_166" FLOAT, 
	"MinorAxis_166" FLOAT, 
	"Orientation_166" FLOAT, 
	"I_174" FLOAT, 
	"MajorAxis_174" FLOAT, 
	"MinorAxis_174" FLOAT, 
	"Orientation_174" FLOAT, 
	"I_181" FLOAT, 
	"MajorAxis_181" FLOAT, 
	"MinorAxis_181" FLOAT, 
	"Orientation_181" FLOAT, 
	"I_189" FLOAT, 
	"MajorAxis_189" FLOAT, 
	"MinorAxis_189" FLOAT, 
	"Orientation_189" FLOAT, 
	"I_197" FLOAT, 
	"MajorAxis_197" FLOAT, 
	"MinorAxis_197" FLOAT, 
	"Orientation_197" FLOAT, 
	"I_204" FLOAT, 
	"MajorAxis_204" FLOAT, 
	"MinorAxis_204" FLOAT, 
	"Orientation_204" FLOAT, 
	"I_212" FLOAT, 
	"MajorAxis_212" FLOAT, 
	"MinorAxis_212" FLOAT, 
	"Orientation_212" FLOAT, 
	"I_220" FLOAT, 
	"MajorAxis_220" FLOAT, 
	"MinorAxis_220" FLOAT, 
	"Orientation_220" FLOAT, 
	"I_227" FLOAT, 
	"MajorAxis_227" FLOAT, 
	"MinorAxis_227" FLOAT, 
	"Orientation_227" FLOAT, 
	PRIMARY KEY (id), 
	CONSTRAINT check_ra_range CHECK (RAJ2000 >= 0 AND RAJ2000 < 360), 
	CONSTRAINT check_dec_range CHECK (DECJ2000 >= -90 AND DECJ2000 <= 90), 
	FOREIGN KEY(version) REFERENCES public.version (id)
)

;

