sonar.projectKey=ska-telescope_sdp_ska-sdp-global-sky-model_cbfbd346-e91b-4746-b466-28d078da3d03
sonar.qualitygate.wait=true
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=build/reports/code-coverage.xml
sonar.python.version=3.10, 3.11
sonar.exclusions=src/ska_sdp_global_sky_model/alembic/**
