"""
Data models for SQLAlchemy

This file is AUTO-GENERATED by scripts/generate_db_schema.py
Generated on: 2026-02-02 11:24:51
Source module: ska_sdp_datamodels.global_sky_model.global_sky_model
ska-sdp-datamodels version: 1.0.2+dev.cdc56e4b4

Database-specific configuration in: scripts/db_config.py

DO NOT EDIT THIS FILE MANUALLY!
To regenerate, run: make generate-schema
"""

# pylint: disable=too-few-public-methods
# pylint: disable=no-member

import logging

from sqlalchemy import BigInteger, Boolean, Column, Float, Integer, String
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import mapped_column

from ska_sdp_global_sky_model.configuration.config import DB_SCHEMA, Base

logger = logging.getLogger(__name__)


class GlobalSkyModelMetadata(Base):
    """Metadata describing a GSM catalogue instance."""

    __table_args__ = {"schema": DB_SCHEMA}

    id = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    # Catalogue version identifier. Semantic versioning is recommended.
    version = Column(String)
    # Reference frequency. Single frequency that represents the band.
    ref_freq = Column(Float)
    # Epoch of observation.
    epoch = Column(String)

    def columns_to_dict(self):
        """
        Return a dictionary representation of a row.
        """
        dict_ = {}
        for key in self.__mapper__.c.keys():
            dict_[key] = getattr(self, key)
        return dict_


class Source(Base):
    """Represents a source in the sky model."""

    __table_args__ = {"schema": DB_SCHEMA}

    id = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    # Name of the source.
    name = Column(String, unique=True)
    # Right ascension of the source.
    ra = Column(Float)
    # Declination of the source.
    dec = Column(Float)
    # I polarization flux at reference frequency(required).
    i_pol = Column(Float)
    # Fitted semi-major axis at reference frequency.
    major_ax = Column(Float, nullable=True)
    # Fitted semi-minor axis at reference frequency.
    minor_ax = Column(Float, nullable=True)
    # Fitted position angle at reference frequency.
    pos_ang = Column(Float, nullable=True)
    # Spectral index polynomial coefficients (up to 5 terms).
    spec_idx = Column(JSON, nullable=True)
    # True if logarithmic spectral model, False if linear.
    log_spec_idx = Column(Boolean, nullable=True)
    # Spectral curvature parameter (alternative model to fitting spectral indices).
    spec_curv = Column(Float, nullable=True)
    # Stokes Q flux.
    q_pol = Column(Float, nullable=True)
    # Stokes U flux.
    u_pol = Column(Float, nullable=True)
    # Stokes V flux.
    v_pol = Column(Float, nullable=True)
    # Polarized fraction.
    pol_frac = Column(Float, nullable=True)
    # Polarization angle (alternative to Q and U).
    pol_ang = Column(Float, nullable=True)
    # Faraday rotation measure.
    rot_meas = Column(Float, nullable=True)
    # HEALPix position for spatial indexing
    healpix_index = Column(BigInteger, index=True, nullable=False)

    def columns_to_dict(self):
        """
        Return a dictionary representation of a row.
        """
        dict_ = {}
        for key in self.__mapper__.c.keys():
            dict_[key] = getattr(self, key)
        return dict_

    def to_json(self):
        """Serializes the instance to a JSON dict."""
        return {
            "name": self.name,
            "coords": (self.ra, self.dec),
            "healpix_index": int(self.healpix_index),
            "i_pol": self.i_pol,
            "major_ax": self.major_ax,
            "minor_ax": self.minor_ax,
            "pos_ang": self.pos_ang,
            "spec_idx": self.spec_idx,
            "log_spec_idx": self.log_spec_idx,
            "spec_curv": self.spec_curv,
            "polarization": {
                "q": self.q_pol,
                "u": self.u_pol,
                "v": self.v_pol,
                "frac": self.pol_frac,
                "ang": self.pol_ang,
                "rot_meas": self.rot_meas,
            },
        }
