"""
Data models for SQLAlchemy

This file is AUTO-GENERATED by scripts/generate_db_schema.py
Generated on: 2026-01-30 12:05:08
Source module: ska_sdp_datamodels.global_sky_model.global_sky_model
ska-sdp-datamodels version: 1.0.2+dev.cdc56e4b4

DO NOT EDIT THIS FILE MANUALLY!
To regenerate, run: make generate-schema
"""

# pylint: disable=too-few-public-methods
# pylint: disable=no-member

import logging

from sqlalchemy import BigInteger, Boolean, Column, Float, Integer, String
from sqlalchemy.dialects.postgresql import JSON, TEXT
from sqlalchemy.orm import mapped_column

from ska_sdp_global_sky_model.configuration.config import DB_SCHEMA, Base

logger = logging.getLogger(__name__)


class Source(Base):
    """Represents a source in the sky model."""

    __table_args__ = {"schema": DB_SCHEMA}

    id = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    # Name of the source.
    name = Column(String, unique=True)
    # Right ascension of the source.
    RAJ2000 = Column(Float)
    # Declination of the source.
    DECJ2000 = Column(Float)
    # I polarization flux at reference frequency(required).
    I_Pol = Column(Float)
    # Fitted semi-major axis at reference frequency.
    Major_Ax = Column(Float, nullable=True)
    # Fitted semi-minor axis at reference frequency.
    Minor_Ax = Column(Float, nullable=True)
    # Fitted position angle at reference frequency.
    Pos_Ang = Column(Float, nullable=True)
    # Spectral index polynomial coefficients (up to 5 terms).
    Spec_Idx = Column(JSON, nullable=True)
    # True if logarithmic spectral model, False if linear.
    Log_Spec_Idx = Column(Boolean, nullable=True)
    # Spectral curvature parameter (alternative model to fitting spectral indices).
    Spec_Curv = Column(Float, nullable=True)
    # Stokes Q flux.
    Q_Pol = Column(Float, nullable=True)
    # Stokes U flux.
    U_Pol = Column(Float, nullable=True)
    # Stokes V flux.
    V_Pol = Column(Float, nullable=True)
    # Polarized fraction.
    Pol_Frac = Column(Float, nullable=True)
    # Polarization angle (alternative to Q and U).
    Pol_Ang = Column(Float, nullable=True)
    # Faraday rotation measure.
    Rot_Meas = Column(Float, nullable=True)
    RAJ2000_Error = Column(Float, nullable=True)
    DECJ2000_Error = Column(Float, nullable=True)
    Heal_Pix_Position = Column(BigInteger, index=True, nullable=False)
    json = Column(TEXT)

    def columns_to_dict(self):
        """
        Return a dictionary representation of a row.
        """
        dict_ = {}
        for key in self.__mapper__.c.keys():
            dict_[key] = getattr(self, key)
        return dict_

    def to_json(self):
        """Serializes the source to a JSON dict."""
        return {
            "name": self.name,
            "coords_J2000": (self.RAJ2000, self.DECJ2000),
            "hpx": int(self.Heal_Pix_Position),
            "i_pol": self.I_Pol,
            "major_ax": self.Major_Ax,
            "minor_ax": self.Minor_Ax,
            "pos_ang": self.Pos_Ang,
            "spec_idx": self.Spec_Idx,
            "polarization": {
                "q": self.Q_Pol,
                "u": self.U_Pol,
                "v": self.V_Pol,
                "frac": self.Pol_Frac,
                "ang": self.Pol_Ang,
            },
        }


class GlobalSkyModelMetadata(Base):
    """Metadata describing a GSM catalogue instance."""

    __table_args__ = {"schema": DB_SCHEMA}

    id = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    # Catalogue version identifier. Semantic versioning is recommended.
    version = Column(String)
    # Reference frequency. Single frequency that represents the band.
    ref_freq = Column(Float)
    # Epoch of observation.
    epoch = Column(String)

    def columns_to_dict(self):
        """
        Return a dictionary representation of a row.
        """
        dict_ = {}
        for key in self.__mapper__.c.keys():
            dict_[key] = getattr(self, key)
        return dict_
