"""create foreignkey to metadata

Revision ID: 0ab09cf0b2b6
Revises: 27fd3ee89965
Create Date: 2026-03-31 10:48:33.684416

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab09cf0b2b6'
down_revision: str | None = '27fd3ee89965'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky_component', sa.Column('gsm_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_public_sky_component_catalogue_name'), table_name='sky_component')
    op.drop_index(op.f('ix_public_sky_component_version'), table_name='sky_component')
    op.drop_constraint(op.f('uq_component_version'), 'sky_component', type_='unique')
    op.create_unique_constraint('uq_component_version', 'sky_component', ['component_id', 'gsm_id'], schema='public')
    op.create_foreign_key(None, 'sky_component', 'global_sky_model_metadata', ['gsm_id'], ['id'], source_schema='public')
    op.drop_column('sky_component', 'version')
    op.drop_column('sky_component', 'catalogue_name')
    op.add_column('sky_component_staging', sa.Column('gsm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sky_component_staging', 'global_sky_model_metadata', ['gsm_id'], ['id'], source_schema='public')
    op.drop_column('sky_component_staging', 'version')
    op.drop_column('sky_component_staging', 'catalogue_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky_component_staging', sa.Column('catalogue_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sky_component_staging', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sky_component_staging', schema='public', type_='foreignkey')
    op.drop_column('sky_component_staging', 'gsm_id')
    op.add_column('sky_component', sa.Column('catalogue_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sky_component', sa.Column('version', sa.VARCHAR(), server_default=sa.text("'0.0.0'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sky_component', schema='public', type_='foreignkey')
    op.drop_constraint('uq_component_version', 'sky_component', schema='public', type_='unique')
    op.create_unique_constraint(op.f('uq_component_version'), 'sky_component', ['component_id', 'version', 'catalogue_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_public_sky_component_version'), 'sky_component', ['version'], unique=False)
    op.create_index(op.f('ix_public_sky_component_catalogue_name'), 'sky_component', ['catalogue_name'], unique=False)
    op.drop_column('sky_component', 'gsm_id')
    # ### end Alembic commands ###
