"""New

Revision ID: 0c62a981493f
Revises: 32a6e8d2afd3
Create Date: 2026-02-19 23:13:16.353579

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c62a981493f'
down_revision: str | None = '32a6e8d2afd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_sky_model_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('catalogue_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('staging', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ref_freq', sa.Float(), nullable=True),
    sa.Column('epoch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_global_sky_model_metadata_id'), 'global_sky_model_metadata', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_global_sky_model_metadata_upload_id'), 'global_sky_model_metadata', ['upload_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_global_sky_model_metadata_version'), 'global_sky_model_metadata', ['version'], unique=True, schema='public')
    op.drop_index(op.f('ix_public_globalskymodelmetadata_id'), table_name='globalskymodelmetadata')
    op.drop_table('globalskymodelmetadata')
    op.add_column('sky_component_staging', sa.Column('version', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sky_component_staging', 'version')
    op.create_table('globalskymodelmetadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ref_freq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('epoch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('globalskymodelmetadata_pkey'))
    )
    op.create_index(op.f('ix_public_globalskymodelmetadata_id'), 'globalskymodelmetadata', ['id'], unique=False)
    op.drop_index(op.f('ix_public_global_sky_model_metadata_version'), table_name='global_sky_model_metadata', schema='public')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_upload_id'), table_name='global_sky_model_metadata', schema='public')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_id'), table_name='global_sky_model_metadata', schema='public')
    op.drop_table('global_sky_model_metadata', schema='public')
    # ### end Alembic commands ###
