"""schema updates and make all fields text

Revision ID: 27fd3ee89965
Revises: 5203c3819ac2
Create Date: 2026-03-31 08:22:45.396913

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fd3ee89965'
down_revision: str | None = '5203c3819ac2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_sky_model_metadata', sa.Column('freq_min_hz', sa.Float(), nullable=True))
    op.add_column('global_sky_model_metadata', sa.Column('freq_max_hz', sa.Float(), nullable=True))
    op.alter_column('global_sky_model_metadata', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('global_sky_model_metadata', 'author',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('global_sky_model_metadata', 'reference',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('global_sky_model_metadata', 'epoch')
    op.add_column('sky_component', sa.Column('source_id', sa.Text(), nullable=True))
    op.add_column('sky_component', sa.Column('epoch', sa.Float(), nullable=True))
    op.add_column('sky_component_staging', sa.Column('source_id', sa.Text(), nullable=True))
    op.add_column('sky_component_staging', sa.Column('epoch', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sky_component_staging', 'epoch')
    op.drop_column('sky_component_staging', 'source_id')
    op.drop_column('sky_component', 'epoch')
    op.drop_column('sky_component', 'source_id')
    op.add_column('global_sky_model_metadata', sa.Column('epoch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('global_sky_model_metadata', 'reference',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('global_sky_model_metadata', 'author',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('global_sky_model_metadata', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('global_sky_model_metadata', 'freq_max_hz')
    op.drop_column('global_sky_model_metadata', 'freq_min_hz')
    # ### end Alembic commands ###
