"""staging

Revision ID: 32a6e8d2afd3
Revises: 7367d297f19c
Create Date: 2026-02-13 09:48:53.279305

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a6e8d2afd3'
down_revision: str | None = '7367d297f19c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sky_component_staging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('healpix_index', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('i_pol', sa.Float(), nullable=True),
    sa.Column('major_ax', sa.Float(), nullable=True),
    sa.Column('minor_ax', sa.Float(), nullable=True),
    sa.Column('pos_ang', sa.Float(), nullable=True),
    sa.Column('spec_idx', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('log_spec_idx', sa.Boolean(), nullable=True),
    sa.Column('q_pol', sa.Float(), nullable=True),
    sa.Column('u_pol', sa.Float(), nullable=True),
    sa.Column('v_pol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'upload_id', name='uq_component_upload'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sky_component_staging_healpix_index'), 'sky_component_staging', ['healpix_index'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_staging_id'), 'sky_component_staging', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_staging_upload_id'), 'sky_component_staging', ['upload_id'], unique=False, schema='public')
    op.add_column('sky_component', sa.Column('version', sa.String(), server_default='0.0.0', nullable=False))
    op.drop_constraint(op.f('sky_component_component_id_key'), 'sky_component', type_='unique')
    op.create_index(op.f('ix_public_sky_component_component_id'), 'sky_component', ['component_id'], unique=False, schema='public')
    op.create_unique_constraint('uq_component_version', 'sky_component', ['component_id', 'version'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_component_version', 'sky_component', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_sky_component_component_id'), table_name='sky_component', schema='public')
    op.create_unique_constraint(op.f('sky_component_component_id_key'), 'sky_component', ['component_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sky_component', 'version')
    op.drop_index(op.f('ix_public_sky_component_staging_upload_id'), table_name='sky_component_staging', schema='public')
    op.drop_index(op.f('ix_public_sky_component_staging_id'), table_name='sky_component_staging', schema='public')
    op.drop_index(op.f('ix_public_sky_component_staging_healpix_index'), table_name='sky_component_staging', schema='public')
    op.drop_table('sky_component_staging', schema='public')
    # ### end Alembic commands ###
