"""Updating nullable for version columns in staging and metadata tables

Revision ID: 5203c3819ac2
Revises: ecd5d36e707a
Create Date: 2026-03-16 11:04:20.094818

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5203c3819ac2'
down_revision: str | None = 'ecd5d36e707a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_sky_model_metadata', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sky_component_staging', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sky_component_staging', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('global_sky_model_metadata', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
