"""New Migration Note

Revision ID: 5e948c5fe753
Revises: 7d5fb33982fa
Create Date: 2026-03-11 10:29:05.542571

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e948c5fe753'
down_revision: str | None = '7d5fb33982fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky_component_staging', sa.Column('catalogue_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sky_component_staging', 'catalogue_name')
    # ### end Alembic commands ###
