"""New upload status table

Revision ID: 64ebd170bb89
Revises: d94590824140
Create Date: 2026-05-25 14:22:49.031056

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ebd170bb89'
down_revision: str | None = 'd94590824140'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadtaskstate',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('upload_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('files_uploaded', sa.Integer(), nullable=False),
        sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_uploadtaskstate_id'), 'uploadtaskstate', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_uploadtaskstate_upload_id'), 'uploadtaskstate', ['upload_id'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_uploadtaskstate_upload_id'), table_name='uploadtaskstate', schema='public')
    op.drop_index(op.f('ix_public_uploadtaskstate_id'), table_name='uploadtaskstate', schema='public')
    op.drop_table('uploadtaskstate', schema='public')
    # ### end Alembic commands ###
