# pylint: disable=all
"""Test

Revision ID: 6ab7861d2188
Revises:
Create Date: 2026-01-23 09:05:38.298483

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ab7861d2188"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("RAJ2000", sa.Float(), nullable=True),
        sa.Column("RAJ2000_Error", sa.Float(), nullable=True),
        sa.Column("DECJ2000", sa.Float(), nullable=True),
        sa.Column("DECJ2000_Error", sa.Float(), nullable=True),
        sa.Column("Heal_Pix_Position", sa.BigInteger(), nullable=False),
        sa.Column("json", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_source_Heal_Pix_Position"),
        "source",
        ["Heal_Pix_Position"],
        unique=False,
        schema="public",
    )
    op.create_index(op.f("ix_public_source_id"), "source", ["id"], unique=False, schema="public")
    op.create_table(
        "telescope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("frequency_min", sa.Float(), nullable=True),
        sa.Column("frequency_max", sa.Float(), nullable=True),
        sa.Column("ingested", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_telescope_id"), "telescope", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "band",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("centre", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("telescope", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telescope"],
            ["public.telescope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(op.f("ix_public_band_id"), "band", ["id"], unique=False, schema="public")
    op.create_table(
        "widebanddata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Bck_Wide", sa.Float(), nullable=True),
        sa.Column("Local_RMS_Wide", sa.Float(), nullable=True),
        sa.Column("Int_Flux_Wide", sa.Float(), nullable=True),
        sa.Column("Int_Flux_Wide_Error", sa.Float(), nullable=True),
        sa.Column("Resid_Mean_Wide", sa.Float(), nullable=True),
        sa.Column("Resid_Sd_Wide", sa.Float(), nullable=True),
        sa.Column("Abs_Flux_Pct_Error", sa.Float(), nullable=True),
        sa.Column("Fit_Flux_Pct_Error", sa.Float(), nullable=True),
        sa.Column("A_PSF_Wide", sa.Float(), nullable=True),
        sa.Column("B_PSF_Wide", sa.Float(), nullable=True),
        sa.Column("PA_PSF_Wide", sa.Float(), nullable=True),
        sa.Column("Spectral_Index", sa.Float(), nullable=True),
        sa.Column("Spectral_Index_Error", sa.Float(), nullable=True),
        sa.Column("A_Wide", sa.Float(), nullable=True),
        sa.Column("A_Wide_Error", sa.Float(), nullable=True),
        sa.Column("B_Wide", sa.Float(), nullable=True),
        sa.Column("B_Wide_Error", sa.Float(), nullable=True),
        sa.Column("PA_Wide", sa.Float(), nullable=True),
        sa.Column("PA_Wide_Error", sa.Float(), nullable=True),
        sa.Column("Flux_Wide", sa.Float(), nullable=True),
        sa.Column("Flux_Wide_Error", sa.Float(), nullable=True),
        sa.Column("Polarised", sa.Boolean(), nullable=True),
        sa.Column("Stokes", sa.String(), nullable=True),
        sa.Column("Rotational_Measure", sa.Float(), nullable=True),
        sa.Column("Rotational_Measure_Error", sa.Float(), nullable=True),
        sa.Column("Fractional_Polarisation", sa.Float(), nullable=True),
        sa.Column("Fractional_Polarisation_Error", sa.Float(), nullable=True),
        sa.Column("Faraday_Complex", sa.Boolean(), nullable=True),
        sa.Column("Spectral_Curvature", sa.Float(), nullable=True),
        sa.Column("Spectral_Curvature_Error", sa.Float(), nullable=True),
        sa.Column("Variable", sa.Boolean(), nullable=True),
        sa.Column("Modulation_Index", sa.Float(), nullable=True),
        sa.Column("Debiased_Modulation_Index", sa.Float(), nullable=True),
        sa.Column("source", sa.Integer(), nullable=True),
        sa.Column("telescope", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source"],
            ["public.source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telescope"],
            ["public.telescope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_widebanddata_id"), "widebanddata", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "narrowbanddata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Bck_Narrow", sa.Float(), nullable=True),
        sa.Column("Local_RMS_Narrow", sa.Float(), nullable=True),
        sa.Column("Int_Flux_Narrow", sa.Float(), nullable=True),
        sa.Column("Int_Flux_Narrow_Error", sa.Float(), nullable=True),
        sa.Column("Resid_Mean_Narrow", sa.Float(), nullable=True),
        sa.Column("Resid_Sd_Narrow", sa.Float(), nullable=True),
        sa.Column("A_PSF_Narrow", sa.Float(), nullable=True),
        sa.Column("B_PSF_Narrow", sa.Float(), nullable=True),
        sa.Column("PA_PSF_Narrow", sa.Float(), nullable=True),
        sa.Column("A_Narrow", sa.Float(), nullable=True),
        sa.Column("A_Narrow_Error", sa.Float(), nullable=True),
        sa.Column("B_Narrow", sa.Float(), nullable=True),
        sa.Column("B_Narrow_Error", sa.Float(), nullable=True),
        sa.Column("PA_Narrow", sa.Float(), nullable=True),
        sa.Column("PA_Narrow_Error", sa.Float(), nullable=True),
        sa.Column("Flux_Narrow", sa.Float(), nullable=True),
        sa.Column("Flux_Narrow_Error", sa.Float(), nullable=True),
        sa.Column("Polarised", sa.Boolean(), nullable=True),
        sa.Column("Stokes", sa.String(), nullable=True),
        sa.Column("Rotational_Measure", sa.Float(), nullable=True),
        sa.Column("Rotational_Measure_Error", sa.Float(), nullable=True),
        sa.Column("Fractional_Polarisation", sa.Float(), nullable=True),
        sa.Column("Fractional_Polarisation_Error", sa.Float(), nullable=True),
        sa.Column("Faraday_Complex", sa.Boolean(), nullable=True),
        sa.Column("Spectral_Index", sa.Float(), nullable=True),
        sa.Column("Spectral_Index_Error", sa.Float(), nullable=True),
        sa.Column("Variable", sa.Boolean(), nullable=True),
        sa.Column("Modulation_Index", sa.Float(), nullable=True),
        sa.Column("Debiased_Modulation_Index", sa.Float(), nullable=True),
        sa.Column("source", sa.Integer(), nullable=True),
        sa.Column("band", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["band"],
            ["public.band.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source"],
            ["public.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_narrowbanddata_id"),
        "narrowbanddata",
        ["id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_narrowbanddata_id"), table_name="narrowbanddata", schema="public"
    )
    op.drop_table("narrowbanddata", schema="public")
    op.drop_index(op.f("ix_public_widebanddata_id"), table_name="widebanddata", schema="public")
    op.drop_table("widebanddata", schema="public")
    op.drop_index(op.f("ix_public_band_id"), table_name="band", schema="public")
    op.drop_table("band", schema="public")
    op.drop_index(op.f("ix_public_telescope_id"), table_name="telescope", schema="public")
    op.drop_table("telescope", schema="public")
    op.drop_index(op.f("ix_public_source_id"), table_name="source", schema="public")
    op.drop_index(op.f("ix_public_source_Heal_Pix_Position"), table_name="source", schema="public")
    op.drop_table("source", schema="public")
    # ### end Alembic commands ###
