"""reindex

Revision ID: 7367d297f19c
Revises: 07a981f1d3ba
Create Date: 2026-02-04 08:12:07.034128

"""
from typing import Sequence

from alembic import op
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '7367d297f19c'
down_revision: str | None = 'f2822a3a3662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(text("DROP INDEX IF EXISTS idx_source_q3c_ipix;"))
    op.execute(text("CREATE EXTENSION IF NOT EXISTS q3c;"))
    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS idx_source_q3c_ipix "
            'ON source (q3c_ang2ipix("ra","dec"));'
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###