"""Index updates

Revision ID: 7d5fb33982fa
Revises: d13f02112837
Create Date: 2026-03-10 13:39:49.443157

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '7d5fb33982fa'
down_revision: str | None = 'd13f02112837'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_q3c_ipix')

    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS idx_source_q3c_ipix "
            'ON sky_component (q3c_ang2ipix("ra_deg","dec_deg"));'
        )
    )
    op.drop_index(op.f('ix_public_global_sky_model_metadata_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_upload_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_version'), table_name='global_sky_model_metadata')
    op.create_unique_constraint('_version_catalogue_name_uc', 'global_sky_model_metadata', ['version', 'catalogue_name'])
    op.create_index(op.f('ix_global_sky_model_metadata_catalogue_name'), 'global_sky_model_metadata', ['catalogue_name'], unique=False)
    op.create_index(op.f('ix_global_sky_model_metadata_id'), 'global_sky_model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_global_sky_model_metadata_upload_id'), 'global_sky_model_metadata', ['upload_id'], unique=True)
    op.create_index(op.f('ix_global_sky_model_metadata_version'), 'global_sky_model_metadata', ['version'], unique=False)
    op.add_column('sky_component', sa.Column('catalogue_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_component_version'), 'sky_component', type_='unique')
    op.create_unique_constraint('uq_component_version', 'sky_component', ['component_id', 'version', 'catalogue_name'], schema='public')
    op.create_index(op.f('ix_public_sky_component_catalogue_name'), 'sky_component', ['catalogue_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_version'), 'sky_component', ['version'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sky_component_version'), table_name='sky_component', schema='public')
    op.drop_index(op.f('ix_public_sky_component_catalogue_name'), table_name='sky_component', schema='public')
    op.drop_constraint('uq_component_version', 'sky_component', schema='public', type_='unique')
    op.create_unique_constraint(op.f('uq_component_version'), 'sky_component', ['component_id', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_column('sky_component', 'catalogue_name')
    op.drop_index(op.f('ix_global_sky_model_metadata_version'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_upload_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_catalogue_name'), table_name='global_sky_model_metadata')
    op.drop_constraint('_version_catalogue_name_uc', 'global_sky_model_metadata', type_='unique')
    op.create_index(op.f('ix_public_global_sky_model_metadata_version'), 'global_sky_model_metadata', ['version'], unique=True)
    op.create_index(op.f('ix_public_global_sky_model_metadata_upload_id'), 'global_sky_model_metadata', ['upload_id'], unique=True)
    op.create_index(op.f('ix_public_global_sky_model_metadata_id'), 'global_sky_model_metadata', ['id'], unique=False)
    op.drop_index('idx_source_q3c_ipix')

    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS idx_source_q3c_ipix "
            'ON sky_component (q3c_ang2ipix("ra","dec"));'
        )
    )
    # ### end Alembic commands ###
