"""New

Revision ID: 878dccc7d809
Revises: 624b22e2fd6a
Create Date: 2026-02-02 14:31:20.521391

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878dccc7d809'
down_revision: str | None = '624b22e2fd6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalskymodelmetadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ref_freq', sa.Float(), nullable=False),
    sa.Column('epoch', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_globalskymodelmetadata_id'), 'globalskymodelmetadata', ['id'], unique=False, schema='public')
    op.drop_index(op.f('ix_public_narrowbanddata_id'), table_name='narrowbanddata')
    op.drop_table('narrowbanddata')
    op.drop_index(op.f('ix_public_band_id'), table_name='band')
    op.drop_table('band')
    op.drop_index(op.f('ix_public_widebanddata_id'), table_name='widebanddata')
    op.drop_table('widebanddata')
    op.drop_index(op.f('ix_public_telescope_id'), table_name='telescope')
    op.drop_table('telescope')
    op.add_column('source', sa.Column('healpix_index', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('source', sa.Column('ra', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('dec', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('i_pol', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('major_ax', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('minor_ax', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('pos_ang', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('spec_idx', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('source', sa.Column('log_spec_idx', sa.Boolean(), nullable=True))
    op.add_column('source', sa.Column('spec_curv', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('q_pol', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('u_pol', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('v_pol', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('pol_frac', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('pol_ang', sa.Float(), nullable=True))
    op.add_column('source', sa.Column('rot_meas', sa.Float(), nullable=True))
    op.alter_column('source', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_public_source_Heal_Pix_Position'), table_name='source')
    op.create_index(op.f('ix_public_source_healpix_index'), 'source', ['healpix_index'], unique=False, schema='public')
    op.drop_column('source', 'DECJ2000_Error')
    op.drop_column('source', 'Heal_Pix_Position')
    op.drop_column('source', 'RAJ2000')
    op.drop_column('source', 'RAJ2000_Error')
    op.drop_column('source', 'DECJ2000')
    op.drop_column('source', 'json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('DECJ2000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('RAJ2000_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('RAJ2000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('source', sa.Column('Heal_Pix_Position', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('source', sa.Column('DECJ2000_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_public_source_healpix_index'), table_name='source', schema='public')
    op.create_index(op.f('ix_public_source_Heal_Pix_Position'), 'source', ['Heal_Pix_Position'], unique=False)
    op.alter_column('source', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('source', 'rot_meas')
    op.drop_column('source', 'pol_ang')
    op.drop_column('source', 'pol_frac')
    op.drop_column('source', 'v_pol')
    op.drop_column('source', 'u_pol')
    op.drop_column('source', 'q_pol')
    op.drop_column('source', 'spec_curv')
    op.drop_column('source', 'log_spec_idx')
    op.drop_column('source', 'spec_idx')
    op.drop_column('source', 'pos_ang')
    op.drop_column('source', 'minor_ax')
    op.drop_column('source', 'major_ax')
    op.drop_column('source', 'i_pol')
    op.drop_column('source', 'dec')
    op.drop_column('source', 'ra')
    op.drop_column('source', 'healpix_index')
    op.create_table('telescope',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frequency_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ingested', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telescope_pkey')),
    sa.UniqueConstraint('name', name=op.f('telescope_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_public_telescope_id'), 'telescope', ['id'], unique=False)
    op.create_table('widebanddata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bck_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Local_RMS_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Int_Flux_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Int_Flux_Wide_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resid_Mean_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resid_Sd_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Abs_Flux_Pct_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fit_Flux_Pct_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_PSF_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_PSF_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_PSF_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Spectral_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Spectral_Index_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_Wide_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_Wide_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_Wide_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Flux_Wide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Flux_Wide_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Polarised', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Stokes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Rotational_Measure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Rotational_Measure_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fractional_Polarisation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fractional_Polarisation_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Faraday_Complex', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Spectral_Curvature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Spectral_Curvature_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Variable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Modulation_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Debiased_Modulation_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telescope', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source'], ['source.id'], name=op.f('widebanddata_source_fkey')),
    sa.ForeignKeyConstraint(['telescope'], ['telescope.id'], name=op.f('widebanddata_telescope_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('widebanddata_pkey'))
    )
    op.create_index(op.f('ix_public_widebanddata_id'), 'widebanddata', ['id'], unique=False)
    op.create_table('band',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('centre', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('telescope', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telescope'], ['telescope.id'], name=op.f('band_telescope_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('band_pkey'))
    )
    op.create_index(op.f('ix_public_band_id'), 'band', ['id'], unique=False)
    op.create_table('narrowbanddata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bck_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Local_RMS_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Int_Flux_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Int_Flux_Narrow_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resid_Mean_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resid_Sd_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_PSF_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_PSF_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_PSF_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A_Narrow_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('B_Narrow_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PA_Narrow_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Flux_Narrow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Flux_Narrow_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Polarised', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Stokes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Rotational_Measure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Rotational_Measure_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fractional_Polarisation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fractional_Polarisation_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Faraday_Complex', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Spectral_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Spectral_Index_Error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Variable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('Modulation_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Debiased_Modulation_Index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('band', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['band'], ['band.id'], name=op.f('narrowbanddata_band_fkey')),
    sa.ForeignKeyConstraint(['source'], ['source.id'], name=op.f('narrowbanddata_source_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('narrowbanddata_pkey'))
    )
    op.create_index(op.f('ix_public_narrowbanddata_id'), 'narrowbanddata', ['id'], unique=False)
    op.drop_index(op.f('ix_public_globalskymodelmetadata_id'), table_name='globalskymodelmetadata', schema='public')
    op.drop_table('globalskymodelmetadata', schema='public')
    # ### end Alembic commands ###
