"""New

Revision ID: a2abbfd9e5ed
Revises: 1a8e0965597b
Create Date: 2026-02-09 14:23:33.031407

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2abbfd9e5ed'
down_revision: str | None = '1a8e0965597b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky_component', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint(op.f('sky_component_component_id_key'), 'sky_component', type_='unique')
    op.create_index(op.f('ix_public_sky_component_component_id'), 'sky_component', ['component_id'], unique=False, schema='public')
    op.create_unique_constraint('uq_component_version', 'sky_component', ['component_id', 'version'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_component_version', 'sky_component', schema='public', type_='unique')
    op.drop_index(op.f('ix_public_sky_component_component_id'), table_name='sky_component', schema='public')
    op.create_unique_constraint(op.f('sky_component_component_id_key'), 'sky_component', ['component_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sky_component', 'version')
    # ### end Alembic commands ###
