"""New

Revision ID: cdcba7972c35
Revises: 5d5a9c279421
Create Date: 2026-02-09 14:09:38.929145

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdcba7972c35'
down_revision: str | None = '5d5a9c279421'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sky_component_staging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('healpix_index', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('i_pol', sa.Float(), nullable=True),
    sa.Column('major_ax', sa.Float(), nullable=True),
    sa.Column('minor_ax', sa.Float(), nullable=True),
    sa.Column('pos_ang', sa.Float(), nullable=True),
    sa.Column('spec_idx', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('log_spec_idx', sa.Boolean(), nullable=True),
    sa.Column('q_pol', sa.Float(), nullable=True),
    sa.Column('u_pol', sa.Float(), nullable=True),
    sa.Column('v_pol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'upload_id', name='uq_component_upload'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sky_component_staging_healpix_index'), 'sky_component_staging', ['healpix_index'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_staging_id'), 'sky_component_staging', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_staging_upload_id'), 'sky_component_staging', ['upload_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sky_component_staging_upload_id'), table_name='sky_component_staging', schema='public')
    op.drop_index(op.f('ix_public_sky_component_staging_id'), table_name='sky_component_staging', schema='public')
    op.drop_index(op.f('ix_public_sky_component_staging_healpix_index'), table_name='sky_component_staging', schema='public')
    op.drop_table('sky_component_staging', schema='public')
    # ### end Alembic commands ###
