"""Column renames

Revision ID: d13f02112837
Revises: 0c62a981493f
Create Date: 2026-03-10 09:59:10.335100

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13f02112837'
down_revision: str | None = '0c62a981493f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_sky_model_metadata', 'ref_freq', new_column_name='ref_freq_hz')
    op.alter_column('sky_component', 'dec', new_column_name='dec_deg')
    op.alter_column('sky_component', 'i_pol', new_column_name='i_pol_jy')
    op.alter_column('sky_component', 'major_ax', new_column_name='major_ax_arcsec')
    op.alter_column('sky_component', 'minor_ax', new_column_name='minor_ax_arcsec')
    op.alter_column('sky_component', 'pos_ang', new_column_name='pos_ang_deg')
    op.alter_column('sky_component', 'q_pol', new_column_name='q_pol_jy')
    op.alter_column('sky_component', 'ra', new_column_name='ra_deg')
    op.alter_column('sky_component', 'u_pol', new_column_name='u_pol_jy')
    op.alter_column('sky_component', 'v_pol', new_column_name='v_pol_jy')
    op.alter_column('sky_component_staging', 'dec', new_column_name='dec_deg')
    op.alter_column('sky_component_staging', 'i_pol', new_column_name='i_pol_jy')
    op.alter_column('sky_component_staging', 'major_ax', new_column_name='major_ax_arcsec')
    op.alter_column('sky_component_staging', 'minor_ax', new_column_name='minor_ax_arcsec')
    op.alter_column('sky_component_staging', 'pos_ang', new_column_name='pos_ang_deg')
    op.alter_column('sky_component_staging', 'q_pol', new_column_name='q_pol_jy')
    op.alter_column('sky_component_staging', 'ra', new_column_name='ra_deg')
    op.alter_column('sky_component_staging', 'u_pol', new_column_name='u_pol_jy')
    op.alter_column('sky_component_staging', 'v_pol', new_column_name='v_pol_jy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sky_component', 'dec_deg', new_column_name='dec')
    op.alter_column('sky_component', 'i_pol_jy', new_column_name='i_pol')
    op.alter_column('sky_component', 'major_ax_arcsec', new_column_name='major_ax')
    op.alter_column('sky_component', 'minor_ax_arcsec', new_column_name='minor_ax')
    op.alter_column('sky_component', 'pos_ang_deg', new_column_name='pos_ang')
    op.alter_column('sky_component', 'q_pol_jy', new_column_name='q_pol')
    op.alter_column('sky_component', 'ra_deg', new_column_name='ra')
    op.alter_column('sky_component', 'u_pol_jy', new_column_name='u_pol')
    op.alter_column('sky_component', 'v_pol_jy', new_column_name='v_pol')
    op.alter_column('sky_component_staging', 'dec_deg', new_column_name='dec')
    op.alter_column('sky_component_staging', 'i_pol_jy', new_column_name='i_pol')
    op.alter_column('sky_component_staging', 'major_ax_arcsec', new_column_name='major_ax')
    op.alter_column('sky_component_staging', 'minor_ax_arcsec', new_column_name='minor_ax')
    op.alter_column('sky_component_staging', 'pos_ang_deg', new_column_name='pos_ang')
    op.alter_column('sky_component_staging', 'q_pol_jy', new_column_name='q_pol')
    op.alter_column('sky_component_staging', 'ra_deg', new_column_name='ra')
    op.alter_column('sky_component_staging', 'u_pol_jy', new_column_name='u_pol')
    op.alter_column('sky_component_staging', 'v_pol_jy', new_column_name='v_pol')
    op.alter_column('global_sky_model_metadata', 'ref_freq_hz', new_column_name='ref_freq')
    # ### end Alembic commands ###
