"""remove healpix column from schemas

Revision ID: d94590824140
Revises: 0ab09cf0b2b6
Create Date: 2026-04-30 15:00:31.650376

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94590824140'
down_revision: str | None = '0ab09cf0b2b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sky_component_healpix_index'), table_name='sky_component')
    op.drop_constraint(op.f('sky_component_gsm_id_fkey'), 'sky_component', type_='foreignkey')
    op.create_foreign_key(None, 'sky_component', 'global_sky_model_metadata', ['gsm_id'], ['id'], source_schema='public')
    op.drop_column('sky_component', 'healpix_index')
    op.drop_index(op.f('ix_public_sky_component_staging_healpix_index'), table_name='sky_component_staging')
    op.drop_constraint(op.f('sky_component_staging_gsm_id_fkey'), 'sky_component_staging', type_='foreignkey')
    op.create_foreign_key(None, 'sky_component_staging', 'global_sky_model_metadata', ['gsm_id'], ['id'], source_schema='public')
    op.drop_column('sky_component_staging', 'healpix_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky_component_staging', sa.Column('healpix_index', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sky_component_staging', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sky_component_staging_gsm_id_fkey'), 'sky_component_staging', 'global_sky_model_metadata', ['gsm_id'], ['id'])
    op.create_index(op.f('ix_public_sky_component_staging_healpix_index'), 'sky_component_staging', ['healpix_index'], unique=False)
    op.add_column('sky_component', sa.Column('healpix_index', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sky_component', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sky_component_gsm_id_fkey'), 'sky_component', 'global_sky_model_metadata', ['gsm_id'], ['id'])
    op.create_index(op.f('ix_public_sky_component_healpix_index'), 'sky_component', ['healpix_index'], unique=False)
    # ### end Alembic commands ###
