"""New

Revision ID: e3808621987c
Revises: 32a6e8d2afd3
Create Date: 2026-02-17 12:10:59.529100

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3808621987c'
down_revision: str | None = '32a6e8d2afd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('catalogue_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ref_freq', sa.Float(), nullable=False, comment='Reference frequency in Hz'),
    sa.Column('epoch', sa.String(), nullable=False, comment='Epoch of observation'),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_metadata_upload_id'), 'catalog_metadata', ['upload_id'], unique=True)
    op.create_index(op.f('ix_catalog_metadata_version'), 'catalog_metadata', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_metadata_version'), table_name='catalog_metadata')
    op.drop_index(op.f('ix_catalog_metadata_upload_id'), table_name='catalog_metadata')
    op.drop_table('catalog_metadata')
    # ### end Alembic commands ###
