"""updated models

Revision ID: ecd5d36e707a
Revises: 0c62a981493f
Create Date: 2026-03-12 08:39:55.022782

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'ecd5d36e707a'
down_revision: str | None = '0c62a981493f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_component_version'), 'sky_component', type_='unique')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_upload_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_public_global_sky_model_metadata_version'), table_name='global_sky_model_metadata')
    op.drop_index('idx_source_q3c_ipix')

    # Migrate ref frequency
    op.drop_column('global_sky_model_metadata', 'ref_freq')
    op.add_column('sky_component', sa.Column('ref_freq_hz', sa.Float(), nullable=True))
    op.add_column('sky_component_staging', sa.Column('ref_freq_hz', sa.Float(), nullable=True))

    # Add catalogue name
    op.add_column('sky_component', sa.Column('catalogue_name', sa.String(), nullable=False))
    op.add_column('sky_component_staging', sa.Column('catalogue_name', sa.String(), nullable=False))

    # Remove deprecated fields
    op.drop_column('sky_component', 'q_pol')
    op.drop_column('sky_component', 'u_pol')
    op.drop_column('sky_component', 'v_pol')
    op.drop_column('sky_component_staging', 'q_pol')
    op.drop_column('sky_component_staging', 'u_pol')
    op.drop_column('sky_component_staging', 'v_pol')

    op.alter_column('sky_component', 'dec', new_column_name='dec_deg')
    op.alter_column('sky_component', 'i_pol', new_column_name='i_pol_jy')
    op.alter_column('sky_component', 'major_ax', new_column_name='a_arcsec')
    op.alter_column('sky_component', 'minor_ax', new_column_name='b_arcsec')
    op.alter_column('sky_component', 'pos_ang', new_column_name='pa_deg')
    op.alter_column('sky_component', 'ra', new_column_name='ra_deg')
    op.alter_column('sky_component_staging', 'dec', new_column_name='dec_deg')
    op.alter_column('sky_component_staging', 'i_pol', new_column_name='i_pol_jy')
    op.alter_column('sky_component_staging', 'major_ax', new_column_name='a_arcsec')
    op.alter_column('sky_component_staging', 'minor_ax', new_column_name='b_arcsec')
    op.alter_column('sky_component_staging', 'pos_ang', new_column_name='pa_deg')
    op.alter_column('sky_component_staging', 'ra', new_column_name='ra_deg')

    op.create_index(op.f('ix_global_sky_model_metadata_catalogue_name'), 'global_sky_model_metadata', ['catalogue_name'], unique=False)
    op.create_index(op.f('ix_global_sky_model_metadata_id'), 'global_sky_model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_global_sky_model_metadata_upload_id'), 'global_sky_model_metadata', ['upload_id'], unique=True)
    op.create_index(op.f('ix_global_sky_model_metadata_version'), 'global_sky_model_metadata', ['version'], unique=False)
    op.create_index(op.f('ix_public_sky_component_catalogue_name'), 'sky_component', ['catalogue_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sky_component_version'), 'sky_component', ['version'], unique=False, schema='public')
    op.create_unique_constraint('_version_catalogue_name_uc', 'global_sky_model_metadata', ['version', 'catalogue_name'])
    op.create_unique_constraint('uq_component_version', 'sky_component', ['component_id', 'version', 'catalogue_name'], schema='public')
    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS idx_source_q3c_ipix "
            'ON sky_component (q3c_ang2ipix("ra_deg","dec_deg"));'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove new indexes
    op.drop_index(op.f('ix_public_sky_component_version'), table_name='sky_component', schema='public')
    op.drop_index(op.f('ix_public_sky_component_catalogue_name'), table_name='sky_component', schema='public')
    op.drop_constraint('uq_component_version', 'sky_component', schema='public', type_='unique')
    op.drop_index(op.f('ix_global_sky_model_metadata_version'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_upload_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_id'), table_name='global_sky_model_metadata')
    op.drop_index(op.f('ix_global_sky_model_metadata_catalogue_name'), table_name='global_sky_model_metadata')
    op.drop_constraint('_version_catalogue_name_uc', 'global_sky_model_metadata', type_='unique')
    op.drop_index('idx_source_q3c_ipix')

    # Remove new fields
    op.drop_column('sky_component', 'ref_freq_hz')
    op.drop_column('sky_component_staging', 'ref_freq_hz')
    op.drop_column('sky_component_staging', 'catalogue_name')
    op.drop_column('sky_component', 'catalogue_name')

    # bring back old fields
    op.add_column('global_sky_model_metadata', sa.Column('ref_freq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sky_component_staging', sa.Column('q_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sky_component_staging', sa.Column('u_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sky_component_staging', sa.Column('v_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # Rename fields
    op.alter_column('sky_component', 'a_arcsec', new_column_name='major_ax')
    op.alter_column('sky_component', 'b_arcsec', new_column_name='minor_ax')
    op.alter_column('sky_component', 'dec_deg', new_column_name='dec')
    op.alter_column('sky_component', 'i_pol_jy', new_column_name='i_pol')
    op.alter_column('sky_component', 'pa_deg', new_column_name='pos_ang')
    op.alter_column('sky_component', 'ra_deg', new_column_name='ra')
    op.alter_column('sky_component_staging', 'a_arcsec', new_column_name='major_ax')
    op.alter_column('sky_component_staging', 'b_arcsec', new_column_name='minor_ax')
    op.alter_column('sky_component_staging', 'dec_deg', new_column_name='dec')
    op.alter_column('sky_component_staging', 'i_pol_jy', new_column_name='i_pol')
    op.alter_column('sky_component_staging', 'pa_deg', new_column_name='pos_ang')
    op.alter_column('sky_component_staging', 'ra_deg', new_column_name='ra')

    # Bring back old indexes
    op.create_unique_constraint(op.f('uq_component_version'), 'sky_component', ['component_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_public_global_sky_model_metadata_version'), 'global_sky_model_metadata', ['version'], unique=True)
    op.create_index(op.f('ix_public_global_sky_model_metadata_upload_id'), 'global_sky_model_metadata', ['upload_id'], unique=True)
    op.create_index(op.f('ix_public_global_sky_model_metadata_id'), 'global_sky_model_metadata', ['id'], unique=False)
    op.add_column('sky_component', sa.Column('q_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sky_component', sa.Column('u_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sky_component', sa.Column('v_pol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.execute(
        text(
            "CREATE INDEX IF NOT EXISTS idx_source_q3c_ipix "
            'ON sky_component (q3c_ang2ipix("ra","dec"));'
        )
    )

    # ### end Alembic commands ###
